#!/bin/bash

curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh

echo >> ~/.bash_profile
echo "eval \"$(/opt/homebrew/bin/brew shellenv)\"" >> ~/.bash_profile
eval "$(/opt/homebrew/bin/brew shellenv)"

brew install --cask raycast
brew install --cask superwhisper

brew install --cask brave-browser
brew install --cask google-chrome
brew install --cask firefox

brew install --cask alacritty
brew install --cask cursor
brew install --cask visual-studio-code

brew install --cask dbeaver-community

brew install --cask discord
brew install --cask slack
brew install --cask zoom
brew install --cask figma

brew install --cask spotify
brew install --cask obsidian
brew install --cask notion

brew install watchman
brew install --cask android-studio
brew install --cask android-platform-tools
brew install --cask vysor
brew install --cask expo-orbit

brew install --cask aws-vpn-client

brew install eza
brew install zoxide
brew install docker
brew install docker-compose
brew install orbstack
brew install mise
brew install gnupg
brew install gh

sudo softwareupdate --instal-rosetta

brew install charmbracelet/tap/crush
brew install charmbracelet/tap/freeze
brew install charmbracelet/tap/mods
brew install charmbracelet/tap/sequin
brew install charmbracelet/tap/vhs
