import = [
  # "~/.local/share/omakub/themes/nord/alacritty.toml",
  # "~/.local/share/omakub/themes/catppuccin/alacritty.toml",
  # "~/.local/share/omakub/themes/everforest/alacritty.toml",
  "~/.local/share/omakub/themes/gruvbox/alacritty.toml",
  # "~/.local/share/omakub/themes/kanagawa/alacritty.toml",
  # "~/.local/share/omakub/themes/tokyo-night/alacritty.toml",
  "~/.config/alacritty/font.toml",
  "~/.config/alacritty/font-size.toml",
  "~/.local/share/omakub/defaults/alacritty.toml"
]
